// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdvkmnatfqiglnzrssdu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkdmttbmF0ZnFpZ2xuenJzc2R1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzODU5NTYsImV4cCI6MjA3MTk2MTk1Nn0.8JWXJuvAM1AnZdthS5HX9kq-GDAKAURawDkELloS25g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});